name: build and push python images

on:
  push:
    branches: [ main ]
    paths:
      - 'dockerfiles/python/*'
  
  workflow_dispatch:

jobs:
  matrix-config:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
        matrix_arr=($(./matrix-gen.sh))
        echo "::set-output name=matrix::{\"include\":[${matrix_arr[@]}]}"
  build-push-images:
    needs: matrix-config
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.matrix-config.outputs.matrix) }}
    steps:
      run: echo ${{ matrix }}