name: build and push python images

on:
  push:
    branches: [ main ]
    paths:
      - 'dockerfiles/python/*'
  
  workflow_dispatch:

jobs:
  matrix-config:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          chmod +x matrix-gen.sh
          matrix_arr=($(./matrix-gen.sh python))
          echo ${matrix_arr[@]}
          echo "::set-output name=matrix::{\"include\":[${matrix_arr[@]}]}"

  build-push-images:
    needs: matrix-config
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.matrix-config.outputs.matrix) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
          with:
            platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ${{ matrix.path }}
          platforms: linux/amd64, linux/arm64, linux/ppc641e
          push: true
          tags: "packageless/python:${{ matrix.tag }}"